//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AuthorizationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorizationService.IAuthorizationService")]
    public interface IAuthorizationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthLogin", ReplyAction="http://tempuri.org/IAuthorizationService/AuthLoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.AuthLoginResponse> AuthLoginAsync(AuthorizationService.AuthLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AuthLoginWebPotal", ReplyAction="http://tempuri.org/IAuthorizationService/AuthLoginWebPotalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.AuthLoginWebPotalResponse> AuthLoginWebPotalAsync(AuthorizationService.AuthLoginWebPotalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/AddUserLoginWebPortal", ReplyAction="http://tempuri.org/IAuthorizationService/AddUserLoginWebPortalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.AddUserLoginWebPortalResponse> AddUserLoginWebPortalAsync(AuthorizationService.AddUserLoginWebPortalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/ExistUserLoginInWebportal", ReplyAction="http://tempuri.org/IAuthorizationService/ExistUserLoginInWebportalResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ExistUserLoginInWebportalAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/ExistUserLoginInApplication", ReplyAction="http://tempuri.org/IAuthorizationService/ExistUserLoginInApplicationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ExistUserLoginInApplicationAsync(int UserID, int AppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/ListAuthLoginRole", ReplyAction="http://tempuri.org/IAuthorizationService/ListAuthLoginRoleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.ListAuthLoginRoleResponse> ListAuthLoginRoleAsync(AuthorizationService.ListAuthLoginRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/Logout", ReplyAction="http://tempuri.org/IAuthorizationService/LogoutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> LogoutAsync(int LogID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/Auth_PdpaApplicationUser_Select", ReplyAction="http://tempuri.org/IAuthorizationService/Auth_PdpaApplicationUser_SelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_PdpaApplicationUser_SelectResponse> Auth_PdpaApplicationUser_SelectAsync(AuthorizationService.Auth_PdpaApplicationUser_SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/PortalTimeAttendanceRegisterSelect", ReplyAction="http://tempuri.org/IAuthorizationService/PortalTimeAttendanceRegisterSelectRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.PortalTimeAttendanceRegisterSelectResponse> PortalTimeAttendanceRegisterSelectAsync(AuthorizationService.PortalTimeAttendanceRegisterSelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/Auth_UserPasswordConfig_Select", ReplyAction="http://tempuri.org/IAuthorizationService/Auth_UserPasswordConfig_SelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_UserPasswordConfig_SelectResponse> Auth_UserPasswordConfig_SelectAsync(AuthorizationService.Auth_UserPasswordConfig_SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizationService/Auth_UserSpecailAccountBlock_Select", ReplyAction="http://tempuri.org/IAuthorizationService/Auth_UserSpecailAccountBlock_SelectRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_UserSpecailAccountBlock_SelectResponse> Auth_UserSpecailAccountBlock_SelectAsync(AuthorizationService.Auth_UserSpecailAccountBlock_SelectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int AppID;
        
        public AuthLoginRequest()
        {
        }
        
        public AuthLoginRequest(string UserName, string Password, int AppID)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.AppID = AppID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.ArrayOfXElement AuthLoginResult;
        
        public AuthLoginResponse()
        {
        }
        
        public AuthLoginResponse(AuthorizationService.ArrayOfXElement AuthLoginResult)
        {
            this.AuthLoginResult = AuthLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthLoginWebPotal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthLoginWebPotalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        public AuthLoginWebPotalRequest()
        {
        }
        
        public AuthLoginWebPotalRequest(string UserName, string Password)
        {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthLoginWebPotalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthLoginWebPotalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.ArrayOfXElement AuthLoginWebPotalResult;
        
        public AuthLoginWebPotalResponse()
        {
        }
        
        public AuthLoginWebPotalResponse(AuthorizationService.ArrayOfXElement AuthLoginWebPotalResult)
        {
            this.AuthLoginWebPotalResult = AuthLoginWebPotalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserLoginWebPortal", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserLoginWebPortalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AppID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIPAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientName;
        
        public AddUserLoginWebPortalRequest()
        {
        }
        
        public AddUserLoginWebPortalRequest(int UserID, int AppID, string ClientIPAddress, string ClientName)
        {
            this.UserID = UserID;
            this.AppID = AppID;
            this.ClientIPAddress = ClientIPAddress;
            this.ClientName = ClientName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserLoginWebPortalResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserLoginWebPortalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddUserLoginWebPortalResult;
        
        public AddUserLoginWebPortalResponse()
        {
        }
        
        public AddUserLoginWebPortalResponse(int AddUserLoginWebPortalResult)
        {
            this.AddUserLoginWebPortalResult = AddUserLoginWebPortalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAuthLoginRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListAuthLoginRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AppID;
        
        public ListAuthLoginRoleRequest()
        {
        }
        
        public ListAuthLoginRoleRequest(int UserID, int AppID)
        {
            this.UserID = UserID;
            this.AppID = AppID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListAuthLoginRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListAuthLoginRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.ArrayOfXElement ListAuthLoginRoleResult;
        
        public ListAuthLoginRoleResponse()
        {
        }
        
        public ListAuthLoginRoleResponse(AuthorizationService.ArrayOfXElement ListAuthLoginRoleResult)
        {
            this.ListAuthLoginRoleResult = ListAuthLoginRoleResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Auth_PdpaApplicationUser_SelectResponseAuth_PdpaApplicationUser_SelectResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_PdpaApplicationUser_Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_PdpaApplicationUser_SelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status;
        
        public Auth_PdpaApplicationUser_SelectRequest()
        {
        }
        
        public Auth_PdpaApplicationUser_SelectRequest(string ApplicationID, string EmpCode, string Status)
        {
            this.ApplicationID = ApplicationID;
            this.EmpCode = EmpCode;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_PdpaApplicationUser_SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_PdpaApplicationUser_SelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.Auth_PdpaApplicationUser_SelectResponseAuth_PdpaApplicationUser_SelectResult Auth_PdpaApplicationUser_SelectResult;
        
        public Auth_PdpaApplicationUser_SelectResponse()
        {
        }
        
        public Auth_PdpaApplicationUser_SelectResponse(AuthorizationService.Auth_PdpaApplicationUser_SelectResponseAuth_PdpaApplicationUser_SelectResult Auth_PdpaApplicationUser_SelectResult)
        {
            this.Auth_PdpaApplicationUser_SelectResult = Auth_PdpaApplicationUser_SelectResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class PortalTimeAttendanceRegisterSelectResponsePortalTimeAttendanceRegisterSelectResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PortalTimeAttendanceRegisterSelect", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PortalTimeAttendanceRegisterSelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StampDateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StampDateTo;
        
        public PortalTimeAttendanceRegisterSelectRequest()
        {
        }
        
        public PortalTimeAttendanceRegisterSelectRequest(string EmpCode, string EmpName, string StampDateFrom, string StampDateTo)
        {
            this.EmpCode = EmpCode;
            this.EmpName = EmpName;
            this.StampDateFrom = StampDateFrom;
            this.StampDateTo = StampDateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PortalTimeAttendanceRegisterSelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PortalTimeAttendanceRegisterSelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.PortalTimeAttendanceRegisterSelectResponsePortalTimeAttendanceRegisterSelectResult PortalTimeAttendanceRegisterSelectResult;
        
        public PortalTimeAttendanceRegisterSelectResponse()
        {
        }
        
        public PortalTimeAttendanceRegisterSelectResponse(AuthorizationService.PortalTimeAttendanceRegisterSelectResponsePortalTimeAttendanceRegisterSelectResult PortalTimeAttendanceRegisterSelectResult)
        {
            this.PortalTimeAttendanceRegisterSelectResult = PortalTimeAttendanceRegisterSelectResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Auth_UserPasswordConfig_SelectResponseAuth_UserPasswordConfig_SelectResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_UserPasswordConfig_Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_UserPasswordConfig_SelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PasswordConfigId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status;
        
        public Auth_UserPasswordConfig_SelectRequest()
        {
        }
        
        public Auth_UserPasswordConfig_SelectRequest(string PasswordConfigId, string Status)
        {
            this.PasswordConfigId = PasswordConfigId;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_UserPasswordConfig_SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_UserPasswordConfig_SelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.Auth_UserPasswordConfig_SelectResponseAuth_UserPasswordConfig_SelectResult Auth_UserPasswordConfig_SelectResult;
        
        public Auth_UserPasswordConfig_SelectResponse()
        {
        }
        
        public Auth_UserPasswordConfig_SelectResponse(AuthorizationService.Auth_UserPasswordConfig_SelectResponseAuth_UserPasswordConfig_SelectResult Auth_UserPasswordConfig_SelectResult)
        {
            this.Auth_UserPasswordConfig_SelectResult = Auth_UserPasswordConfig_SelectResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Auth_UserSpecailAccountBlock_SelectResponseAuth_UserSpecailAccountBlock_SelectResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_UserSpecailAccountBlock_Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_UserSpecailAccountBlock_SelectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status;
        
        public Auth_UserSpecailAccountBlock_SelectRequest()
        {
        }
        
        public Auth_UserSpecailAccountBlock_SelectRequest(string EmpCode, string Status)
        {
            this.EmpCode = EmpCode;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Auth_UserSpecailAccountBlock_SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Auth_UserSpecailAccountBlock_SelectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuthorizationService.Auth_UserSpecailAccountBlock_SelectResponseAuth_UserSpecailAccountBlock_SelectResult Auth_UserSpecailAccountBlock_SelectResult;
        
        public Auth_UserSpecailAccountBlock_SelectResponse()
        {
        }
        
        public Auth_UserSpecailAccountBlock_SelectResponse(AuthorizationService.Auth_UserSpecailAccountBlock_SelectResponseAuth_UserSpecailAccountBlock_SelectResult Auth_UserSpecailAccountBlock_SelectResult)
        {
            this.Auth_UserSpecailAccountBlock_SelectResult = Auth_UserSpecailAccountBlock_SelectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IAuthorizationServiceChannel : AuthorizationService.IAuthorizationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AuthorizationServiceClient : System.ServiceModel.ClientBase<AuthorizationService.IAuthorizationService>, AuthorizationService.IAuthorizationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthorizationServiceClient() : 
                base(AuthorizationServiceClient.GetDefaultBinding(), AuthorizationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthorizationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthorizationServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthorizationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthorizationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthorizationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.AuthLoginResponse> AuthorizationService.IAuthorizationService.AuthLoginAsync(AuthorizationService.AuthLoginRequest request)
        {
            return base.Channel.AuthLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.AuthLoginResponse> AuthLoginAsync(string UserName, string Password, int AppID)
        {
            AuthorizationService.AuthLoginRequest inValue = new AuthorizationService.AuthLoginRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.AppID = AppID;
            return ((AuthorizationService.IAuthorizationService)(this)).AuthLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.AuthLoginWebPotalResponse> AuthorizationService.IAuthorizationService.AuthLoginWebPotalAsync(AuthorizationService.AuthLoginWebPotalRequest request)
        {
            return base.Channel.AuthLoginWebPotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.AuthLoginWebPotalResponse> AuthLoginWebPotalAsync(string UserName, string Password)
        {
            AuthorizationService.AuthLoginWebPotalRequest inValue = new AuthorizationService.AuthLoginWebPotalRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            return ((AuthorizationService.IAuthorizationService)(this)).AuthLoginWebPotalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.AddUserLoginWebPortalResponse> AuthorizationService.IAuthorizationService.AddUserLoginWebPortalAsync(AuthorizationService.AddUserLoginWebPortalRequest request)
        {
            return base.Channel.AddUserLoginWebPortalAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.AddUserLoginWebPortalResponse> AddUserLoginWebPortalAsync(int UserID, int AppID, string ClientIPAddress, string ClientName)
        {
            AuthorizationService.AddUserLoginWebPortalRequest inValue = new AuthorizationService.AddUserLoginWebPortalRequest();
            inValue.UserID = UserID;
            inValue.AppID = AppID;
            inValue.ClientIPAddress = ClientIPAddress;
            inValue.ClientName = ClientName;
            return ((AuthorizationService.IAuthorizationService)(this)).AddUserLoginWebPortalAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> ExistUserLoginInWebportalAsync(int UserID)
        {
            return base.Channel.ExistUserLoginInWebportalAsync(UserID);
        }
        
        public System.Threading.Tasks.Task<int> ExistUserLoginInApplicationAsync(int UserID, int AppID)
        {
            return base.Channel.ExistUserLoginInApplicationAsync(UserID, AppID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.ListAuthLoginRoleResponse> AuthorizationService.IAuthorizationService.ListAuthLoginRoleAsync(AuthorizationService.ListAuthLoginRoleRequest request)
        {
            return base.Channel.ListAuthLoginRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.ListAuthLoginRoleResponse> ListAuthLoginRoleAsync(int UserID, int AppID)
        {
            AuthorizationService.ListAuthLoginRoleRequest inValue = new AuthorizationService.ListAuthLoginRoleRequest();
            inValue.UserID = UserID;
            inValue.AppID = AppID;
            return ((AuthorizationService.IAuthorizationService)(this)).ListAuthLoginRoleAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> LogoutAsync(int LogID)
        {
            return base.Channel.LogoutAsync(LogID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_PdpaApplicationUser_SelectResponse> AuthorizationService.IAuthorizationService.Auth_PdpaApplicationUser_SelectAsync(AuthorizationService.Auth_PdpaApplicationUser_SelectRequest request)
        {
            return base.Channel.Auth_PdpaApplicationUser_SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.Auth_PdpaApplicationUser_SelectResponse> Auth_PdpaApplicationUser_SelectAsync(string ApplicationID, string EmpCode, string Status)
        {
            AuthorizationService.Auth_PdpaApplicationUser_SelectRequest inValue = new AuthorizationService.Auth_PdpaApplicationUser_SelectRequest();
            inValue.ApplicationID = ApplicationID;
            inValue.EmpCode = EmpCode;
            inValue.Status = Status;
            return ((AuthorizationService.IAuthorizationService)(this)).Auth_PdpaApplicationUser_SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.PortalTimeAttendanceRegisterSelectResponse> AuthorizationService.IAuthorizationService.PortalTimeAttendanceRegisterSelectAsync(AuthorizationService.PortalTimeAttendanceRegisterSelectRequest request)
        {
            return base.Channel.PortalTimeAttendanceRegisterSelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.PortalTimeAttendanceRegisterSelectResponse> PortalTimeAttendanceRegisterSelectAsync(string EmpCode, string EmpName, string StampDateFrom, string StampDateTo)
        {
            AuthorizationService.PortalTimeAttendanceRegisterSelectRequest inValue = new AuthorizationService.PortalTimeAttendanceRegisterSelectRequest();
            inValue.EmpCode = EmpCode;
            inValue.EmpName = EmpName;
            inValue.StampDateFrom = StampDateFrom;
            inValue.StampDateTo = StampDateTo;
            return ((AuthorizationService.IAuthorizationService)(this)).PortalTimeAttendanceRegisterSelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_UserPasswordConfig_SelectResponse> AuthorizationService.IAuthorizationService.Auth_UserPasswordConfig_SelectAsync(AuthorizationService.Auth_UserPasswordConfig_SelectRequest request)
        {
            return base.Channel.Auth_UserPasswordConfig_SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.Auth_UserPasswordConfig_SelectResponse> Auth_UserPasswordConfig_SelectAsync(string PasswordConfigId, string Status)
        {
            AuthorizationService.Auth_UserPasswordConfig_SelectRequest inValue = new AuthorizationService.Auth_UserPasswordConfig_SelectRequest();
            inValue.PasswordConfigId = PasswordConfigId;
            inValue.Status = Status;
            return ((AuthorizationService.IAuthorizationService)(this)).Auth_UserPasswordConfig_SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthorizationService.Auth_UserSpecailAccountBlock_SelectResponse> AuthorizationService.IAuthorizationService.Auth_UserSpecailAccountBlock_SelectAsync(AuthorizationService.Auth_UserSpecailAccountBlock_SelectRequest request)
        {
            return base.Channel.Auth_UserSpecailAccountBlock_SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthorizationService.Auth_UserSpecailAccountBlock_SelectResponse> Auth_UserSpecailAccountBlock_SelectAsync(string EmpCode, string Status)
        {
            AuthorizationService.Auth_UserSpecailAccountBlock_SelectRequest inValue = new AuthorizationService.Auth_UserSpecailAccountBlock_SelectRequest();
            inValue.EmpCode = EmpCode;
            inValue.Status = Status;
            return ((AuthorizationService.IAuthorizationService)(this)).Auth_UserSpecailAccountBlock_SelectAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizationService))
            {
				string SgAuthorize;
				var builder = new ConfigurationBuilder()
						.SetBasePath(Directory.GetCurrentDirectory())
						.AddJsonFile("appSettings.json", optional: true, reloadOnChange: true);
				IConfiguration _configuration = builder.Build();
				SgAuthorize =_configuration.GetConnectionString("SgAuthorize");
				return new System.ServiceModel.EndpointAddress(SgAuthorize);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthorizationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthorizationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthorizationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthorizationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthorizationService,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.1.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
